service: incrementific

provider:
  name: aws
  runtime: nodejs12.x
  environment: ${file(env.yml):${self:provider.stage}, file(env.yml):dev}

functions:
  authorize:
    handler: lib/auth-policy.handler
  register:
    handler: register.handler
    events:
      - http:
          path: register
          method: post
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
          authorizer: authorize
package:
  individually: true